# Generated by Django 5.2.6 on 2025-09-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
