# Generated by Django 5.2.6 on 2025-09-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
