# Generated by Django 5.2.6 on 2025-09-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
